# syntax=docker/dockerfile:1.7

###############################################################################
# AgentBox — multi-stage build producing a tiny, non-root standalone image.
# Relies on Next.js `output: "standalone"` (see next.config.ts).
###############################################################################

# finding 4: pin the base image to the immutable node:22-alpine manifest
# digest (multi-arch OCI index). A bare tag is mutable and could resolve to a
# different — possibly compromised — image between builds. Verify/update with:
#   docker buildx imagetools inspect node:22-alpine
# then replace the digest below; the tag stays for human readability.
ARG NODE_VERSION=22-alpine@sha256:c610fcdfb1d5b4740dd70c284ed3cb16bb857e0f7166196e36a5501df7a3aa32

# 1. deps — install production+dev deps once, cached on package*.json changes.
FROM node:${NODE_VERSION} AS deps
WORKDIR /app
# libc6-compat: some native-ish npm deps expect glibc symbols on Alpine.
RUN apk add --no-cache libc6-compat
COPY package.json package-lock.json ./
RUN --mount=type=cache,target=/root/.npm \
    npm ci

# 2. builder — compile the Next.js app into .next/standalone.
FROM node:${NODE_VERSION} AS builder
WORKDIR /app
ENV NEXT_TELEMETRY_DISABLED=1
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build

# 3. runner — only the standalone server + static assets + public/.
FROM node:${NODE_VERSION} AS runner
WORKDIR /app
ENV NODE_ENV=production \
    NEXT_TELEMETRY_DISABLED=1 \
    PORT=3000 \
    HOSTNAME=0.0.0.0

# Run as the unprivileged `node` user that ships with the base image.
COPY --from=builder --chown=node:node /app/public ./public
COPY --from=builder --chown=node:node /app/.next/standalone ./
COPY --from=builder --chown=node:node /app/.next/static ./.next/static

USER node
EXPOSE 3000

# Lightweight healthcheck against the app's own HTTP server.
HEALTHCHECK --interval=30s --timeout=5s --start-period=20s --retries=3 \
    CMD node -e "fetch('http://127.0.0.1:'+(process.env.PORT||3000)+'/login').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))"

# server.js is generated by Next's standalone output.
CMD ["node", "server.js"]
